version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.production
    # command: npm run migrate
    networks:
      - backend

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rest_api_chat
      PGDATA: .:/docker-entrypoint-initdb.d
    volumes:
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
